### ISSUE TITLE
Channel 4: Time Team - Unable to download Season 01, Episode 4

### ISSUE THREAD

**Issue by evbuk1** [stabbedbybrick/freevine#56]
**Describe the bug**
I get an error when I try to download Time Team Season 1 Episode 04 (https://www.channel4.com/programmes/time-team/on-demand/16521-004)

**To Reproduce**
To invoke:
```
python freevine.py get --episode https://www.channel4.com/programmes/time-team/on-demand/16521-00
```

Result:
```
❯_freevine v1.1.1

19:40:13.851 INFO : ALL4
19:40:13.851 INFO : + Loading user profile
19:40:13.853 INFO : Using cached tokens
Traceback (most recent call last):
  File "/home/evan.brown/Desktop/freevine/freevine.py", line 15, in <module>
    cli()
  File "/home/evan.brown/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/evan.brown/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/evan.brown/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evan.brown/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evan.brown/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/evan.brown/Desktop/freevine/utils/commands.py", line 81, in get
    Service(config, **kwargs)
  File "/home/evan.brown/Desktop/freevine/services/channel4/channel4.py", line 63, in __init__
    self.get_options()
  File "/home/evan.brown/Desktop/freevine/services/channel4/channel4.py", line 378, in get_options
    self.download(download, title, bearer)
  File "/home/evan.brown/Desktop/freevine/services/channel4/channel4.py", line 381, in download
    self.res, manifest, token = self.get_mediainfo(stream.id, self.quality, bearer)
  File "/home/evan.brown/Desktop/freevine/services/channel4/channel4.py", line 306, in get_mediainfo
    heights, self.soup = get_heights(self.client, manifest)
  File "/home/evan.brown/Desktop/freevine/utils/utilities.py", line 125, in get_heights
    r.raise_for_status()
  File "/home/evan.brown/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ak.dash01.stream.c4assets.com/wvmod-stream/CH4_33_05_42_16521004001002_002.mpd?c3.ri=13494009089843244131
```

**Expected behavior**
The episode should download without error.

**Comment by evbuk1** [comment]
Ah, it just worked.  I think Channel 4 uses rate limiting...

Is it possible to add a delay in the script to prevent this?  Tidal-DL does this for downloading songs from Tidal without a too many requests error.

**Comment by BobHasNoSoul** [comment]
can confirm channel 4 does have a rate limit... specifically user request limit, if you request too many pages and files too quickly from the same ip you get temp banned and that error is thrown.

my logical way to combat this was a longwinded one 

create a bash script (im running ubuntu so not sure about windows)

sudo python3 freevine.py get --threads 1 -e S01E01 urlhere
sleep 240
sudo python3 freevine.py get --threads 1 -e S01E02 urlhere
sleep 240
sudo python3 freevine.py get --threads 1 -e S01E03 urlhere
sleep 240
sudo python3 freevine.py get --threads 1 -e S01E04 urlhere
sleep 240
sudo python3 freevine.py get --threads 1 -e S01E05 urlhere
sleep 240
sudo python3 freevine.py get --threads 1 -e S01E06 urlhere
sleep 240


this does three things, limit the download requests to one thread and it forces it to get a specific episode instead of going via complete, which can error with the 400 rate limit, it then gets the episode and when done sleeps for 240 seconds before attempting the next episode

**Comment by stabbedbybrick** [comment]
Yeah, looks like you're right. After doing some quick tests, it looks like there's a request limit per 60s. But there might not be a need for sleep. By lowering the --threads to 2, I was allowed to download 10+ episodes without any issues. The standard setting is 16, so that's a big difference. 

Experiment with the thread count and see if you can find a sweet spot that won't go over the limit.

**Comment by evbuk1** [comment]
Reducing the threads does help but the process still crashes with a 400 on a long complete series download.  Maybe we could have a retry mechanism on bad request which incorporates a sleep?

Also I have noticed that if you do a complete download invocation and it crashes, repeating the same command skips downloading existing episodes but the process generates a 400 from Channel 4 sooner than the last existing file.  I think this means that a request is being made to the C4 server even where the episode already exists in the download folder.  An improvement would be to check for an existing file first before a server call is made.  get-iplayer uses a cache system to achieve the same effect.

**Comment by stabbedbybrick** [comment]
After doing a bunch of tests, I can't find a pattern to their limit. Sometimes, I'm allowed 10 seasons in a row, sometimes only 10 episodes. And when it finally does hit that limit, sleeping for even 10+ minutes doesn't solve it. And since the same 400 errors are thrown when using a bad VPN/proxy, adding a bad request sleep/retry function would make things confusing.  The best solution would probably be something similar to what @BobHasNoSoul is doing, and add a --slowdown option that lets the user set a specified sleep between downloads to avoid hitting a rate limit to begin with. 

The episode cache is a great suggestion, though. I've been working on a system that caches downloads based on id and quality, which allows for checks before any API requests and doesn't have to rely on filenames. It'll hopefully be added in the next version.

**Comment by stabbedbybrick** [comment]
An improved cache system and a `--slowdown` option has now been added in the latest version.

**Comment by evbuk1** [comment]
Thanks very much!
